# Docker Hub
[[registry]]
prefix = "docker.io"
location = "docker.io"

[[registry.mirror]]
location = "dockerproxy.net"

[[registry.mirror]]
location = "hub1.nat.tf"

[[registry.mirror]]
location = "dockerproxy.cool"

[[registry.mirror]]
location = "docker.kejilion.pro"

[[registry.mirror]]
location = "docker.1ms.run"


# GitHub Container Registry
[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"

[[registry.mirror]]
location = "ghcr.nju.edu.cn"

[[registry.mirror]]
location = "ghcr.dockerproxy.net"

[[registry.mirror]]
location = "ghcr.1ms.run"
